name: Cloud Hypervisor Build
on: [pull_request, create]

env:
  CLOUD_HYPERVISOR_REF: v50.0
  VFIO_BINDINGS_REF: vfio-bindings-v0.6.0

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Cloud Hypervisor Build using MSHV changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Code checkout
        uses: actions/checkout@v6
        with:
          path: mshv

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Cloning Cloud Hypervisor Repo
        uses: actions/checkout@v6
        with:
          repository: cloud-hypervisor/cloud-hypervisor
          ref: ${{ env.CLOUD_HYPERVISOR_REF }}
          path: cloud-hypervisor

      - name: Cloning vfio Repo
        uses: actions/checkout@v6
        with:
          repository: rust-vmm/vfio
          ref: ${{ env.VFIO_BINDINGS_REF }}
          path: vfio

      - name: Copying script to vfio directory
        working-directory: ./mshv
        run: cp scripts/use-local-mshv-for-vfio-build.sh ../vfio/

      - name: Copying script to CLH directory
        working-directory: ./mshv
        run: cp scripts/use-local-mshv-for-clh-build.sh ../cloud-hypervisor/
  
      - name: Applying patch(to use local mshv crates) with script
        working-directory: ./cloud-hypervisor
        run: ./use-local-mshv-for-clh-build.sh

      - name: Applying patch(to use local mshv crates) with script
        working-directory: ./vfio
        run: ./use-local-mshv-for-vfio-build.sh

      - name: Build Cloud-Hypervisor(mshv,kvm)
        working-directory: ./cloud-hypervisor
        run: cargo build --release --all --no-default-features --features mshv,kvm

      - name: Build Cloud-Hypervisor(sev_snp)
        working-directory: ./cloud-hypervisor
        run: cargo build --release --all --no-default-features --features sev_snp

      - name: Clippy(kvm,mshv)
        working-directory: ./cloud-hypervisor
        run: cargo clippy --locked --all --all-targets --no-default-features --tests --examples --features "mshv,kvm" -- -D warnings -D clippy::undocumented_unsafe_blocks

      - name: Clippy(sev_snp)
        working-directory: ./cloud-hypervisor
        run: cargo clippy --locked --all --all-targets --no-default-features --tests --examples --features "sev_snp" -- -D warnings -D clippy::undocumented_unsafe_blocks